<?php

/**
 * Opciones de la barra lateral del panel de administración.
 */
return [
    ['title' => '<i class="fa fa-tachometer" aria-hidden="true"></i> Información',
        'id' => 'admin',
        'href' => 'admin',
        'sub' => false,
    ],
    ['title' => '<span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span> Entradas',
        'id' => 'post',
        'href' => 'admin/post',
        'sub' => [
            ['title' => '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Nueva entrada',
                'href' => 'admin/post/insert',
                'sub' => false,
            ],
            ['title' => '<span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span> Categorías',
                'href' => 'admin/category',
                'sub' => false,
            ],
//            ['title' => '<span class="glyphicon glyphicon-tags" aria-hidden="true"></span> Etiquetas',
//                'href' => 'admin/term',
//                'sub' => false,
//            ],
        ],
    ],
//    ['title' => '<span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span> Paginas',
//        'id' => 'page',
//        'href' => 'admin/page',
//        'sub' => [
//            ['title' => '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Nueva pagina',
//                'href' => 'admin/page/insert',
//                'sub' => false,
//            ],
//        ],
//    ],
//    ['title' => '<span class="glyphicon glyphicon-home" aria-hidden="true"></span> Barra lateral',
//        'id' => 'sidebar',
//        'href' => 'admin/sidebar',
//        'sub' => false,
//    ],
//    ['title' => '<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Menus',
//        'id' => 'menu',
//        'href' => 'admin/menu',
//        'sub' => false,
//    ],
    ['title' => '<span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comentarios',
        'id' => 'comment',
        'href' => 'admin/comment',
        'sub' => false,
    ],
    ['title' => '<span class="glyphicon glyphicon-user" aria-hidden="true"></span> Usuarios',
        'id' => 'user',
        'href' => 'admin/user',
        'sub' => [
            ['title' => '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Nuevo usuario',
                'href' => 'admin/user/insert',
                'sub' => false,
            ],
        ],
    ],
    ['title' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Configuración',
        'id' => 'option',
        'href' => 'admin/option',
        'sub' => false,
    ],
];
