<?php
/**
 * LicenseController.php
 */

namespace SoftnCMS\controllers\admin;

use SoftnCMS\controllers\CUDControllerAbstract;
use SoftnCMS\controllers\ViewController;
use SoftnCMS\models\managers\LicensesManager;

/**
 * Class LicenseController
 * @author Nicolás Marulanda P.
 */
class LicenseController extends CUDControllerAbstract {
    
    public function create() {
        // TODO: Implement create() method.
    }
    
    public function update($id) {
        // TODO: Implement update() method.
    }
    
    public function delete($id) {
        parent::delete($id); // TODO: Change the autogenerated stub
    }
    
    protected function form() {
        // TODO: Implement form() method.
    }
    
    protected function filterInputs() {
        // TODO: Implement filterInputs() method.
    }
    
    protected function read() {
        $licensesManager = new LicensesManager();
        
        ViewController::sendViewData('licenses', $licensesManager->read());
    }
}
