<?php
/**
 * ProfileController.php
 */

namespace SoftnCMS\controllers\admin;

use SoftnCMS\controllers\CUDControllerAbstract;
use SoftnCMS\controllers\ViewController;
use SoftnCMS\models\managers\ProfilesManager;

/**
 * Class ProfileController
 * @author Nicolás Marulanda P.
 */
class ProfileController extends CUDControllerAbstract {
    
    public function create() {
        // TODO: Implement create() method.
    }
    
    public function update($id) {
        // TODO: Implement update() method.
    }
    
    public function delete($id) {
        parent::delete($id); // TODO: Change the autogenerated stub
    }
    
    protected function form() {
        // TODO: Implement form() method.
    }
    
    protected function filterInputs() {
        // TODO: Implement filterInputs() method.
    }
    
    protected function read() {
        $profilesManager = new ProfilesManager();
        
        ViewController::sendViewData('profiles', $profilesManager->read());
    }
    
}
