-- CONTENDO DE EJEMPLO -- http://www.generatedata.com/
-- USE softn_cms;

-- SN_USERS

INSERT INTO {DB_PREFIX}users (user_login,user_name,user_email,user_rol,user_registred,user_pass,user_url) 
VALUES 
("Deirdre","Stephen","In@elitEtiam.edu",3,"2014-12-03 06:00:54","TWZ12FJA3NV","http://Deirdre.com"),
("Blair","Patrick","aliquam@eleifendCras.edu",3,"2007-12-17 12:48:41","YYD60QDO6SG","http://Blair.com"),
("Tashya","Gisela","aliquam.enim@feugiatnonlobortis.edu",3,"2012-07-08 01:22:43","HZW89MJE3JH","http://Tashya.com"),
("Honorato","Addison","a@turpisnon.ca",0,"2011-06-02 05:47:43","XZR11ARJ8HD","http://Honorato.com"),
("Fletcher","Chancellor","arcu@ac.edu",3,"2001-01-12 19:20:53","BSV58VFW8XQ","http://Fletcher.com"),
("Germane","Victor","Donec@Aliquamnisl.net",0,"2013-09-03 00:50:06","YBW84SGR2JN","http://Germane.com"),
("Lance","Stella","laoreet.lectus.quis@rutrumeu.org",3,"2002-10-31 04:13:37","QPL09WKY3UT","http://Lance.com"),
("Richard","Eve","eget.mollis@indolor.com",0,"2004-01-20 03:19:59","JQI57KJD8PM","http://Richard.com"),
("Buffy","Leah","et@velitdui.co.uk",3,"2014-06-30 12:21:05","GXA61PSO0AR","http://Buffy.com"),
("Cassidy","Arthur","leo@Maurismagna.org",0,"2002-05-28 23:47:31","XBB53HFN9WX","http://Cassidy.com"),
("Brandon","Indigo","hendrerit@iaculisaliquetdiam.ca",3,"2012-10-16 04:14:12","DZE00SIZ9FK","http://Brandon.com"),
("Jaime","Ronan","lectus.Cum@maurisanunc.co.uk",3,"2014-07-09 08:30:35","YSY92ZOX0HK","http://Jaime.com"),
("Dawn","Guy","Nunc@tinciduntnibhPhasellus.org",1,"2015-05-11 01:42:21","VYE59EKR4IS","http://Dawn.com"),
("Martha","Geoffrey","Curabitur.sed@ornare.co.uk",3,"2002-10-31 08:33:59","OBK01YXO5RN","http://Martha.com"),
("Avye","Camilla","Phasellus.ornare@lacinia.ca",2,"2013-10-12 02:36:03","OIZ19NYD7FX","http://Avye.com"),
("Harlan","Kyle","neque.non.quam@nonfeugiat.com",1,"2001-07-29 18:30:14","UAQ08GTH3BT","http://Harlan.com"),
("Caryn","Desiree","elit.Etiam@bibendumsedest.org",3,"2001-12-08 13:28:03","AVC52YQD8XM","http://Caryn.com"),
("Maxwell","Jamal","et.magna.Praesent@volutpat.ca",1,"2010-07-15 21:30:41","FTT40MHI4VH","http://Maxwell.com"),
("Vladimir","Ora","varius.et@nibh.net",3,"2012-08-17 20:32:39","GMZ24IOO4UR","http://Vladimir.com"),
("MacKensie","India","Suspendisse@QuisquevariusNam.ca",2,"2015-03-31 05:12:03","EKI70WLI2DT","http://MacKensie.com"),
("Rhoda","Jael","non.sollicitudin.a@vellectusCum.co.uk",2,"2008-10-11 13:22:43","KLZ99MKI0HE","http://Rhoda.com"),
("Drake","Tobias","nunc.ullamcorper@Donec.com",1,"2002-03-26 18:59:55","QIS07BKF9ZM","http://Drake.com"),
("Tana","Stella","egestas.lacinia.Sed@quisturpis.co.uk",3,"2001-03-24 03:35:37","AZH40LEW1DT","http://Tana.com"),
("Allen","Colleen","luctus@lectusCum.ca",2,"2011-08-04 20:24:56","EBN25MFZ3KK","http://Allen.com"),
("Aimee","Brendan","scelerisque.sed@idblanditat.edu",2,"2014-03-21 05:45:23","TRR17WSE5TA","http://Aimee.com"),
("Phyllis","Ross","hymenaeos@Cumsociis.edu",3,"2003-04-07 10:53:39","TKL55ZWI2GQ","http://Phyllis.com"),
("Gail","Alea","eleifend@etrutrumeu.ca",0,"2001-04-17 16:07:00","EMN57LNP6FH","http://Gail.com"),
("Keelie","Kylie","lorem.vitae@magnisdis.com",3,"2010-09-29 17:15:56","NXM72QBR7UP","http://Keelie.com"),
("Jamal","Blossom","Cum@enimEtiam.org",1,"2009-04-11 22:47:48","WDJ37ZYL3AM","http://Jamal.com"),
("Julie","Abbot","elit.a@aliquameuaccumsan.ca",1,"2009-09-01 09:51:45","ZCH87MRI2UH","http://Julie.com"),
("Sacha","Herrod","ligula.eu@Sed.ca",0,"2015-12-30 19:04:18","ORW40TTI7ZI","http://Sacha.com"),
("Jena","Hayley","pharetra.nibh@tempordiamdictum.org",1,"2015-01-29 01:16:08","KFG35HJZ7ZM","http://Jena.com"),
("Kelly","Belle","amet.orci.Ut@Nunc.ca",0,"2004-11-23 01:12:11","KLR44GTC8YG","http://Kelly.com"),
("Abigail","Tanek","malesuada.vel@mauris.com",0,"2011-08-21 08:30:36","GCH46CIK4VB","http://Abigail.com"),
("Ross","Noah","tellus@luctusaliquet.org",2,"2006-10-22 19:22:56","QHL50AXX7JI","http://Ross.com"),
("Quyn","Evan","erat@suscipit.edu",0,"2012-07-10 01:25:15","VNC70GWT5RE","http://Quyn.com"),
("Lareina","Thor","In@tortorIntegeraliquam.net",0,"2004-04-22 12:52:45","UZM40URM6FU","http://Lareina.com"),
("Elijah","Shaeleigh","ante.blandit@magnisdis.co.uk",3,"2015-03-16 01:23:32","XXG19YEM8JO","http://Elijah.com"),
("Althea","Owen","vulputate.ullamcorper@at.edu",1,"2002-04-08 02:55:09","VRC85URL0PJ","http://Althea.com"),
("Chester","Drew","id.sapien@semNullainterdum.ca",3,"2014-02-01 03:50:40","XIG96RZB3JV","http://Chester.com"),
("Lani","Dara","dignissim@molestieintempus.ca",3,"2002-07-19 13:45:34","ACA38PTC8NB","http://Lani.com"),
("Dexter","Giselle","hymenaeos.Mauris.ut@Phasellus.com",3,"2011-08-21 22:11:44","TBS39RDH0SF","http://Dexter.com"),
("Madonna","Hilel","velit.Pellentesque.ultricies@suscipitnonummyFusce.net",0,"2009-05-22 08:38:04","INO35TBX5XQ","http://Madonna.com"),
("Vera","Barry","nisi@auctorquis.edu",0,"2005-06-22 13:32:58","MSE09XMQ8RN","http://Vera.com"),
("Rana","Aiko","at@Morbi.ca",3,"2012-10-08 00:35:19","OOG11UMD6GL","http://Rana.com"),
("Dana","Gretchen","odio@dolorquam.org",3,"2003-02-21 22:08:32","LTL96MCA3EO","http://Dana.com"),
("Amelia","Alexander","eu@variusNamporttitor.ca",1,"2011-10-15 23:21:17","YYC32QPA1FT","http://Amelia.com"),
("Charissa","Drake","eu.augue@necmollisvitae.co.uk",0,"2002-07-27 04:07:37","OZN36HQD7GV","http://Charissa.com"),
("Simon","Ursa","Sed@pharetra.ca",0,"2006-01-13 05:15:05","JGF04ALG9MZ","http://Simon.com"),
("Jillian","Phelan","sem.egestas.blandit@magnisdisparturient.org",2,"2002-07-05 21:53:53","XIG20JTY8BZ","http://Jillian.com");

-- SN_POSTS

CREATE FUNCTION get_id_user_post(inTable VARCHAR(45)) RETURNS INT
BEGIN
	DECLARE queryID INT;
    CASE inTable
		WHEN "{DB_PREFIX}users" THEN
			SELECT ID INTO queryID FROM {DB_PREFIX}users ORDER BY RAND() LIMIT 1;
		WHEN "{DB_PREFIX}posts" THEN
			SELECT ID INTO queryID FROM {DB_PREFIX}posts ORDER BY RAND() LIMIT 1;
    END CASE;
    RETURN queryID;
END;

INSERT INTO {DB_PREFIX}posts (post_title,post_status,post_date,post_contents,comment_status,users_ID,post_type) 
VALUES 
("gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum.",1,"2004-08-06 18:26:12","elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices",0,"2012-09-29 04:32:12","neque sed sem egestas blandit. Nam nulla magna, malesuada vel,",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui",0,"2013-02-27 20:42:19","amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("ante ipsum",0,"2005-05-24 16:18:51","sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam",0,"2014-10-04 04:15:23","Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("ultrices, mauris ipsum porta elit, a feugiat",1,"2000-11-30 21:34:24","vitae velit egestas lacinia. Sed congue, elit sed consequat auctor,",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.",0,"2012-02-14 02:00:11","tempor lorem, eget mollis lectus pede et risus. Quisque libero",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut",1,"2013-09-07 19:47:44","at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan",0,"2006-07-26 10:04:13","tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("ridiculus mus. Aenean eget",1,"2005-03-03 22:39:54","magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed,",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris",1,"2000-08-08 19:43:44","mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam",1,"2012-08-21 16:53:34","blandit enim consequat purus. Maecenas libero est, congue a, aliquet",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra",1,"2009-02-21 13:14:34","faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare.",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.",0,"2009-11-28 11:20:13","cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat.",0,"2004-07-19 19:30:50","lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare",1,"2015-09-15 12:27:53","sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis,",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac",1,"2009-02-02 13:11:22","urna justo faucibus lectus, a sollicitudin orci sem eget massa.",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,",1,"2011-08-05 20:08:35","cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales",0,"2005-03-29 18:57:26","dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("Donec vitae erat vel pede",0,"2016-03-06 02:17:38","sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales.",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor",1,"2004-09-08 15:44:42","neque. Nullam ut nisi a odio semper cursus. Integer mollis.",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante",1,"2013-10-12 22:01:06","ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies",0,"2009-04-05 02:37:52","ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.",1,"2012-11-07 12:20:55","a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas",0,"2013-03-05 16:41:18","enim diam vel arcu. Curabitur ut odio vel est tempor",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("justo eu arcu. Morbi sit amet massa. Quisque porttitor",1,"2007-07-05 15:11:26","dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum",1,"2009-07-28 02:47:23","malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas,",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras",0,"2015-08-31 23:20:16","sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.",0,"2002-09-09 00:11:57","id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("at,",1,"2002-06-09 01:25:03","est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("nulla at sem molestie sodales. Mauris blandit enim",0,"2015-05-17 04:18:32","risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,",0,"2004-02-02 04:43:14","ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis.",0,"2002-05-31 02:40:04","Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("ac tellus. Suspendisse sed dolor. Fusce mi lorem,",0,"2007-10-05 15:14:35","fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non",1,"2002-03-03 00:16:04","elementum sem, vitae aliquam eros turpis non enim. Mauris quis",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,",0,"2013-09-28 11:23:54","fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("eu, odio. Phasellus at augue id",1,"2012-12-29 07:03:00","volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis",0,"2002-05-14 13:15:53","orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus.",1,"2011-12-24 15:37:03","feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris",1,"2006-04-21 08:00:28","malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor.",1,"2015-02-27 03:18:08","ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla",1,"2002-12-02 19:52:54","Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc",1,"2002-12-28 12:51:33","diam. Pellentesque habitant morbi tristique senectus et netus et malesuada",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("vitae risus. Duis a mi",0,"2008-05-21 08:17:33","odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a,",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis,",0,"2014-06-21 00:24:55","amet ornare lectus justo eu arcu. Morbi sit amet massa.",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi",0,"2008-09-15 06:28:02","ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui",1,"2001-09-30 10:03:47","ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula.",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("lacus. Mauris",0,"2007-07-13 09:18:28","Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis",0,get_id_user_post("{DB_PREFIX}users"),"post"),
("nec, diam. Duis mi enim, condimentum eget, volutpat",0,"2013-05-25 04:51:07","elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et",1,get_id_user_post("{DB_PREFIX}users"),"post"),
("Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu",1,"2006-11-24 17:41:28","consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus",0,get_id_user_post("{DB_PREFIX}users"),"post");

INSERT INTO {DB_PREFIX}posts (post_title,post_status,post_date,post_contents,comment_status,users_ID,post_type) 
VALUES 
("gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum.",1,"2004-08-06 18:26:12","elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices",0,"2012-09-29 04:32:12","neque sed sem egestas blandit. Nam nulla magna, malesuada vel,",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui",0,"2013-02-27 20:42:19","amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("ante ipsum",0,"2005-05-24 16:18:51","sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam",0,"2014-10-04 04:15:23","Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("ultrices, mauris ipsum porta elit, a feugiat",1,"2000-11-30 21:34:24","vitae velit egestas lacinia. Sed congue, elit sed consequat auctor,",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.",0,"2012-02-14 02:00:11","tempor lorem, eget mollis lectus pede et risus. Quisque libero",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut",1,"2013-09-07 19:47:44","at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan",0,"2006-07-26 10:04:13","tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("ridiculus mus. Aenean eget",1,"2005-03-03 22:39:54","magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed,",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris",1,"2000-08-08 19:43:44","mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam",1,"2012-08-21 16:53:34","blandit enim consequat purus. Maecenas libero est, congue a, aliquet",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra",1,"2009-02-21 13:14:34","faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare.",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.",0,"2009-11-28 11:20:13","cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat.",0,"2004-07-19 19:30:50","lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare",1,"2015-09-15 12:27:53","sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis,",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac",1,"2009-02-02 13:11:22","urna justo faucibus lectus, a sollicitudin orci sem eget massa.",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,",1,"2011-08-05 20:08:35","cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales",0,"2005-03-29 18:57:26","dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("Donec vitae erat vel pede",0,"2016-03-06 02:17:38","sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales.",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor",1,"2004-09-08 15:44:42","neque. Nullam ut nisi a odio semper cursus. Integer mollis.",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante",1,"2013-10-12 22:01:06","ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies",0,"2009-04-05 02:37:52","ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.",1,"2012-11-07 12:20:55","a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas",0,"2013-03-05 16:41:18","enim diam vel arcu. Curabitur ut odio vel est tempor",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("justo eu arcu. Morbi sit amet massa. Quisque porttitor",1,"2007-07-05 15:11:26","dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum",1,"2009-07-28 02:47:23","malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas,",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras",0,"2015-08-31 23:20:16","sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.",0,"2002-09-09 00:11:57","id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("at,",1,"2002-06-09 01:25:03","est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("nulla at sem molestie sodales. Mauris blandit enim",0,"2015-05-17 04:18:32","risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,",0,"2004-02-02 04:43:14","ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis.",0,"2002-05-31 02:40:04","Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("ac tellus. Suspendisse sed dolor. Fusce mi lorem,",0,"2007-10-05 15:14:35","fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non",1,"2002-03-03 00:16:04","elementum sem, vitae aliquam eros turpis non enim. Mauris quis",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,",0,"2013-09-28 11:23:54","fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("eu, odio. Phasellus at augue id",1,"2012-12-29 07:03:00","volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis",0,"2002-05-14 13:15:53","orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus.",1,"2011-12-24 15:37:03","feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris",1,"2006-04-21 08:00:28","malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor.",1,"2015-02-27 03:18:08","ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla",1,"2002-12-02 19:52:54","Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc",1,"2002-12-28 12:51:33","diam. Pellentesque habitant morbi tristique senectus et netus et malesuada",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("vitae risus. Duis a mi",0,"2008-05-21 08:17:33","odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a,",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis,",0,"2014-06-21 00:24:55","amet ornare lectus justo eu arcu. Morbi sit amet massa.",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi",0,"2008-09-15 06:28:02","ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui",1,"2001-09-30 10:03:47","ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula.",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("lacus. Mauris",0,"2007-07-13 09:18:28","Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis",0,get_id_user_post("{DB_PREFIX}users"),"page"),
("nec, diam. Duis mi enim, condimentum eget, volutpat",0,"2013-05-25 04:51:07","elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et",1,get_id_user_post("{DB_PREFIX}users"),"page"),
("Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu",1,"2006-11-24 17:41:28","consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus",0,get_id_user_post("{DB_PREFIX}users"),"page");

-- SN_CATEGORIES

INSERT INTO {DB_PREFIX}categories (category_name, category_description) 
VALUES 
("YXO69IHL4MH","pede, ultrices a, auctor non, feugiat nec, diam. Duis mi"),
("RLL34IIL1UM","natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."),
("FVT73RFQ4SV","arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt"),
("UYT93MTW1TQ","convallis, ante lectus convallis est, vitae sodales nisi magna sed"),
("LRZ14OVJ7UO","dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse"),
("RKE66ICG7TI","vel arcu eu odio tristique pharetra. Quisque ac libero nec"),
("MNK92ZAU3RX","rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,"),
("EUQ02QXV9UH","ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor."),
("GQD88QUW7IE","elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu"),
("QOJ75BFV6IR","metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus"),
("CSS25DFJ1AG","tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget"),
("HTD16RHY5QL","arcu ac orci. Ut semper pretium neque. Morbi quis urna."),
("FNF51HHS1EG","lacus pede sagittis augue, eu tempor erat neque non quam."),
("XVQ44XKA9TX","a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc"),
("GEN66JST2VW","nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras"),
("OMT61VXI3WA","ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero"),
("LUV08SAL9ER","dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus"),
("QXD05VZY3KK","orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique"),
("SLO99EUG6YX","et risus. Quisque libero lacus, varius et, euismod et, commodo"),
("DHV37ZUL8LK","enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum,"),
("BDY48YOE4OA","mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean"),
("IFJ20MYP1DD","ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer"),
("QDZ75TPL9YN","sit amet ornare lectus justo eu arcu. Morbi sit amet"),
("RMF35SMI4OK","Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie"),
("UYC08KHL2YD","sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices"),
("YWB93EAY0DU","et magnis dis parturient montes, nascetur ridiculus mus. Proin vel"),
("OCD09XWC1NP","libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus"),
("ONF06IZX8OB","risus, at fringilla purus mauris a nunc. In at pede."),
("WVF06ZJW2TI","scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit"),
("NJJ41UOU9SS","Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non,"),
("PKF10WST4KR","egestas nunc sed libero. Proin sed turpis nec mauris blandit"),
("ATG05GTK7CM","fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor,"),
("UXE84KKE7AV","et nunc. Quisque ornare tortor at risus. Nunc ac sem"),
("XXR91UEY9HH","lacinia orci, consectetuer euismod est arcu ac orci. Ut semper"),
("WQB41IBY4FX","condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing"),
("FCV56KJS6MZ","elit fermentum risus, at fringilla purus mauris a nunc. In"),
("CYL15SDN2HX","neque sed sem egestas blandit. Nam nulla magna, malesuada vel,"),
("IOO83FWY5SG","lobortis. Class aptent taciti sociosqu ad litora torquent per conubia"),
("NQV08VOH8TX","euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas"),
("ZDB95KQN2KR","ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris"),
("OTA99KIR5KC","posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse"),
("OFO72CUO6PM","ac nulla. In tincidunt congue turpis. In condimentum. Donec at"),
("IJP06NYH8CJ","mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec,"),
("HPI45SRN9EO","ipsum primis in faucibus orci luctus et ultrices posuere cubilia"),
("PPR24GMV1SO","amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus"),
("SKT73TTK2RE","elit, a feugiat tellus lorem eu metus. In lorem. Donec"),
("JTV58PMI1EL","orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras"),
("SRS31ZYP0ZW","orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna"),
("TFA13TOM0KO","sem, vitae aliquam eros turpis non enim. Mauris quis turpis"),
("SFZ25DNB1YR","neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc");

-- SN_TERMS

INSERT INTO {DB_PREFIX}terms (term_name,term_description) 
VALUES 
("YXO69IHL4MH","pede, ultrices a, auctor non, feugiat nec, diam. Duis mi"),
("RLL34IIL1UM","natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."),
("FVT73RFQ4SV","arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt"),
("UYT93MTW1TQ","convallis, ante lectus convallis est, vitae sodales nisi magna sed"),
("LRZ14OVJ7UO","dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse"),
("RKE66ICG7TI","vel arcu eu odio tristique pharetra. Quisque ac libero nec"),
("MNK92ZAU3RX","rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,"),
("EUQ02QXV9UH","ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor."),
("GQD88QUW7IE","elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu"),
("QOJ75BFV6IR","metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus"),
("CSS25DFJ1AG","tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget"),
("HTD16RHY5QL","arcu ac orci. Ut semper pretium neque. Morbi quis urna."),
("FNF51HHS1EG","lacus pede sagittis augue, eu tempor erat neque non quam."),
("XVQ44XKA9TX","a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc"),
("GEN66JST2VW","nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras"),
("OMT61VXI3WA","ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero"),
("LUV08SAL9ER","dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus"),
("QXD05VZY3KK","orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique"),
("SLO99EUG6YX","et risus. Quisque libero lacus, varius et, euismod et, commodo"),
("DHV37ZUL8LK","enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum,"),
("BDY48YOE4OA","mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean"),
("IFJ20MYP1DD","ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer"),
("QDZ75TPL9YN","sit amet ornare lectus justo eu arcu. Morbi sit amet"),
("RMF35SMI4OK","Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie"),
("UYC08KHL2YD","sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices"),
("YWB93EAY0DU","et magnis dis parturient montes, nascetur ridiculus mus. Proin vel"),
("OCD09XWC1NP","libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus"),
("ONF06IZX8OB","risus, at fringilla purus mauris a nunc. In at pede."),
("WVF06ZJW2TI","scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit"),
("NJJ41UOU9SS","Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non,"),
("PKF10WST4KR","egestas nunc sed libero. Proin sed turpis nec mauris blandit"),
("ATG05GTK7CM","fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor,"),
("UXE84KKE7AV","et nunc. Quisque ornare tortor at risus. Nunc ac sem"),
("XXR91UEY9HH","lacinia orci, consectetuer euismod est arcu ac orci. Ut semper"),
("WQB41IBY4FX","condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing"),
("FCV56KJS6MZ","elit fermentum risus, at fringilla purus mauris a nunc. In"),
("CYL15SDN2HX","neque sed sem egestas blandit. Nam nulla magna, malesuada vel,"),
("IOO83FWY5SG","lobortis. Class aptent taciti sociosqu ad litora torquent per conubia"),
("NQV08VOH8TX","euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas"),
("ZDB95KQN2KR","ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris"),
("OTA99KIR5KC","posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse"),
("OFO72CUO6PM","ac nulla. In tincidunt congue turpis. In condimentum. Donec at"),
("IJP06NYH8CJ","mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec,"),
("HPI45SRN9EO","ipsum primis in faucibus orci luctus et ultrices posuere cubilia"),
("PPR24GMV1SO","amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus"),
("SKT73TTK2RE","elit, a feugiat tellus lorem eu metus. In lorem. Donec"),
("JTV58PMI1EL","orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras"),
("SRS31ZYP0ZW","orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna"),
("TFA13TOM0KO","sem, vitae aliquam eros turpis non enim. Mauris quis turpis"),
("SFZ25DNB1YR","neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc");

-- SN_COMMENTS

INSERT INTO {DB_PREFIX}comments (comment_status,comment_autor,comment_author_email,comment_date,comment_contents,post_ID) VALUES (0,"Veronica Santana","ut.dolor@Fusce.com","2005-10-18 14:38:59","nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus",get_id_user_post("{DB_PREFIX}posts")),
(1,"Gemma Diaz","ante.ipsum@luctusCurabitur.edu","2016-01-25 14:13:06","eget laoreet posuere, enim nisl elementum purus, accumsan interdum libero",get_id_user_post("{DB_PREFIX}posts")),
(0,"Reese Kline","fringilla@molestiepharetranibh.org","2004-10-22 03:13:53","ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam",get_id_user_post("{DB_PREFIX}posts")),
(1,"Isaac Klein","urna.Nunc@ipsumportaelit.com","2011-12-09 05:26:32","luctus lobortis. Class aptent taciti sociosqu ad litora torquent per",get_id_user_post("{DB_PREFIX}posts")),
(0,"Mallory Pace","dolor@lobortisnisinibh.co.uk","2005-02-07 04:16:54","egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est",get_id_user_post("{DB_PREFIX}posts")),
(0,"Scarlett Vincent","orci.Donec.nibh@ullamcorper.net","2008-09-11 04:14:30","enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum",get_id_user_post("{DB_PREFIX}posts")),
(1,"Ali Buckner","lobortis.augue@anteblandit.com","2000-12-28 03:10:26","Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra.",get_id_user_post("{DB_PREFIX}posts")),
(1,"Caesar Glenn","montes.nascetur@orci.com","2002-03-25 21:49:25","mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean",get_id_user_post("{DB_PREFIX}posts")),
(1,"Lael Leach","Morbi.accumsan@quis.co.uk","2013-02-18 18:21:08","elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris",get_id_user_post("{DB_PREFIX}posts")),
(0,"Britanni Jones","Nullam.suscipit.est@acfacilisisfacilisis.net","2011-01-24 18:35:58","id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor,",get_id_user_post("{DB_PREFIX}posts")),
(0,"Aidan Peterson","felis.Donec@Cumsociis.ca","2016-02-29 19:19:04","Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor",get_id_user_post("{DB_PREFIX}posts")),
(0,"Wanda Russo","iaculis.quis.pede@vehiculaPellentesquetincidunt.ca","2015-08-24 04:49:26","scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed",get_id_user_post("{DB_PREFIX}posts")),
(1,"Selma Duffy","amet@tellus.co.uk","2005-08-01 17:19:20","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,",get_id_user_post("{DB_PREFIX}posts")),
(0,"Laurel Underwood","odio.Aliquam@pretium.org","2001-12-17 16:57:51","Nam nulla magna, malesuada vel, convallis in, cursus et, eros.",get_id_user_post("{DB_PREFIX}posts")),
(0,"Wang Rivas","tincidunt.nunc@Proin.org","2014-02-01 05:54:36","nunc. In at pede. Cras vulputate velit eu sem. Pellentesque",get_id_user_post("{DB_PREFIX}posts")),
(0,"Julian Giles","interdum.feugiat@dis.com","2008-10-12 08:48:11","dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,",get_id_user_post("{DB_PREFIX}posts")),
(1,"Lunea Terry","ultricies@nullaat.ca","2002-05-22 19:19:20","consectetuer euismod est arcu ac orci. Ut semper pretium neque.",get_id_user_post("{DB_PREFIX}posts")),
(0,"Stewart Butler","Quisque.porttitor@maurisid.co.uk","2000-12-11 23:52:40","mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor",get_id_user_post("{DB_PREFIX}posts")),
(1,"Linda Rogers","Duis@feugiatnec.org","2006-09-29 16:02:41","sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra,",get_id_user_post("{DB_PREFIX}posts")),
(0,"Indira Lott","a@lacuspedesagittis.co.uk","2011-03-10 12:38:29","magna a neque. Nullam ut nisi a odio semper cursus.",get_id_user_post("{DB_PREFIX}posts")),
(0,"Zephania Hewitt","ut.cursus@nisimagnased.ca","2012-09-27 18:18:37","non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh.",get_id_user_post("{DB_PREFIX}posts")),
(0,"Sara Warner","sociosqu.ad.litora@nequevenenatislacus.com","2008-10-12 03:20:45","commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies",get_id_user_post("{DB_PREFIX}posts")),
(0,"Ronan Dixon","nisi@Fusce.edu","2010-07-23 04:10:34","leo elementum sem, vitae aliquam eros turpis non enim. Mauris",get_id_user_post("{DB_PREFIX}posts")),
(1,"Grady Riggs","ultrices.Vivamus.rhoncus@nullaIn.net","2008-02-05 19:39:07","Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus",get_id_user_post("{DB_PREFIX}posts")),
(1,"Odysseus Tate","a.enim@idliberoDonec.org","2009-01-22 15:48:53","risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a",get_id_user_post("{DB_PREFIX}posts")),
(0,"Natalie Contreras","Duis.elementum.dui@malesuadafames.co.uk","2008-05-12 08:09:52","vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac",get_id_user_post("{DB_PREFIX}posts")),
(1,"Anjolie Holloway","sem.magna@bibendum.edu","2009-09-20 00:54:27","blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus",get_id_user_post("{DB_PREFIX}posts")),
(0,"Ulric Hebert","Nam.tempor.diam@faucibusid.org","2011-02-26 02:31:12","et risus. Quisque libero lacus, varius et, euismod et, commodo",get_id_user_post("{DB_PREFIX}posts")),
(0,"Flavia Noble","lectus.sit@sapien.net","2001-05-14 20:09:34","neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc",get_id_user_post("{DB_PREFIX}posts")),
(1,"Vladimir Salazar","pede.nec@ut.ca","2013-05-20 13:06:44","id risus quis diam luctus lobortis. Class aptent taciti sociosqu",get_id_user_post("{DB_PREFIX}posts")),
(0,"Glenna Avery","orci.adipiscing.non@molestiepharetra.ca","2007-11-21 23:26:27","orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero",get_id_user_post("{DB_PREFIX}posts")),
(1,"Eleanor Flowers","ullamcorper.eu.euismod@fringillaDonec.ca","2015-10-14 02:41:55","adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor",get_id_user_post("{DB_PREFIX}posts")),
(0,"Cadman Greer","tempor@sit.net","2002-03-14 04:38:40","Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu.",get_id_user_post("{DB_PREFIX}posts")),
(1,"Darrel Briggs","lacus.varius@magnis.co.uk","2005-11-13 13:12:30","lorem vitae odio sagittis semper. Nam tempor diam dictum sapien.",get_id_user_post("{DB_PREFIX}posts")),
(0,"Samson Dale","a.ultricies@enimnectempus.com","2011-08-19 13:21:18","ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede.",get_id_user_post("{DB_PREFIX}posts")),
(1,"Mollie Jones","lobortis@tinciduntorci.co.uk","2005-04-10 18:53:23","adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque",get_id_user_post("{DB_PREFIX}posts")),
(0,"Carol Ratliff","gravida@eleifendnec.ca","2010-08-28 12:28:57","amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor",get_id_user_post("{DB_PREFIX}posts")),
(1,"Dalton Mccullough","commodo@euturpisNulla.edu","2007-05-12 05:42:28","lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc",get_id_user_post("{DB_PREFIX}posts")),
(1,"Josiah Hurst","eu@Vivamussit.ca","2003-01-22 14:03:09","magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu",get_id_user_post("{DB_PREFIX}posts")),
(0,"Victoria Barry","ultricies.adipiscing@Crasdolor.com","2002-01-14 16:15:52","laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi",get_id_user_post("{DB_PREFIX}posts")),
(0,"Phyllis Sims","nonummy.ultricies@dui.ca","2011-05-31 04:45:31","non nisi. Aenean eget metus. In nec orci. Donec nibh.",get_id_user_post("{DB_PREFIX}posts")),
(1,"Ruby Nicholson","velit.Aliquam@orci.co.uk","2015-02-15 05:56:34","massa non ante bibendum ullamcorper. Duis cursus, diam at pretium",get_id_user_post("{DB_PREFIX}posts")),
(1,"Germane Lane","aliquet.nec@etmagnis.org","2011-06-02 23:38:18","nulla at sem molestie sodales. Mauris blandit enim consequat purus.",get_id_user_post("{DB_PREFIX}posts")),
(0,"Tasha Baxter","quis.lectus@euismodin.org","2012-09-07 16:09:04","Quisque ornare tortor at risus. Nunc ac sem ut dolor",get_id_user_post("{DB_PREFIX}posts")),
(1,"Mia Michael","eget.magna.Suspendisse@tellusNunc.org","2009-07-20 07:40:31","Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique",get_id_user_post("{DB_PREFIX}posts")),
(0,"Leila Vargas","ut.mi.Duis@natoque.net","2001-11-02 15:07:16","Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin",get_id_user_post("{DB_PREFIX}posts")),
(0,"Flynn Valencia","semper.tellus.id@nonluctus.net","2001-09-18 05:44:46","volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean",get_id_user_post("{DB_PREFIX}posts")),
(1,"Vanna Clarke","venenatis@mifelisadipiscing.org","2007-08-26 14:25:51","Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris",get_id_user_post("{DB_PREFIX}posts")),
(1,"Sierra Hanson","gravida@mi.ca","2007-05-19 11:18:45","Curabitur egestas nunc sed libero. Proin sed turpis nec mauris",get_id_user_post("{DB_PREFIX}posts")),
(0,"Ariana Odom","Curae.Phasellus.ornare@libero.org","2008-04-20 18:27:56","mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id",get_id_user_post("{DB_PREFIX}posts"));
    
DROP FUNCTION get_id_user_post;

-- SN_POSTS_CATEGORIES TERMS

CREATE PROCEDURE posts_categories_terms()
BEGIN
    DECLARE post_ID INT;
    DECLARE category_ID INT;
    DECLARE term_ID INT;
    DECLARE count INT DEFAULT 1;
    
    WHILE count <= 50 DO
		SELECT ID INTO post_ID FROM {DB_PREFIX}posts WHERE post_type = 'post' AND ID NOT IN (SELECT relationships_post_ID FROM {DB_PREFIX}posts_categories) AND ID NOT IN (SELECT relationships_post_ID FROM {DB_PREFIX}posts_terms) ORDER BY RAND() LIMIT 1;
		SELECT ID INTO category_ID FROM {DB_PREFIX}categories ORDER BY RAND() LIMIT 1;
		SELECT ID INTO term_ID FROM {DB_PREFIX}terms ORDER BY RAND() LIMIT 1;
		
		INSERT INTO {DB_PREFIX}posts_categories (`relationships_post_ID`, `relationships_category_ID`) VALUES (post_ID, category_ID);
		INSERT INTO {DB_PREFIX}posts_terms (`relationships_post_ID`, `relationships_term_ID`) VALUES (post_ID, term_ID);
		SET count = count + 1;
    END WHILE;
END;

CALL posts_categories_terms();
DROP PROCEDURE posts_categories_terms;